#!/usr/bin/env bash
rm -f APL.jar
rm -rf src/build/APL
cd src
mkdir -p build
javac -encoding UTF-8 -Xmaxerrs 1000 -d ./build $(find APL -name '*.java')
cd build
jar cvfe APL.jar APL.Main * > /dev/null
mv APL.jar ../../APL.jar
